name: carfix_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  go_router: ^14.3.0
  alice: ^1.0.0-dev.12
  shared_preferences: ^2.3.2
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  pinput: ^5.0.0
  injectable: ^2.5.0
  get_it: ^8.0.3
  freezed: ^3.0.6
  retrofit: ^4.4.2
  dio: ^5.8.0+1
  carfix_localization:
    path: carfix_localization
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  provider: ^6.1.4
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.4
  retrofit_generator: ^9.1.9

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
